name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATA: ${{ fromJson(secrets.DATA) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ env.DATA.key1 }}
      