name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - id: data
        run: |
          echo "::set-output name=parsed::$(echo ${{ secrets.DATA }} | jq '.failure')"
      - run: echo "${{ steps.data.outputs.parsed }}"
      