name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: data
        run: |
          test=$(cat static.json | jq -r '.failure')
          echo "::set-output name=parsed::${test}"
      - run: echo ${{ steps.data.outputs.parsed }}